"""added new tables

Revision ID: 2b4782dcfced
Revises: 266446f2be2d
Create Date: 2021-03-11 12:57:51.482705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b4782dcfced'
down_revision = '266446f2be2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('contractid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('availability', sa.DateTime(), nullable=False),
    sa.Column('capacity_in_days', sa.Integer(), nullable=False),
    sa.Column('hours_of_work', sa.Integer(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('sub_sector', sa.String(), nullable=False),
    sa.Column('skill_set', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('about', sa.String(), nullable=False),
    sa.Column('resume', sa.String(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profileid'], ),
    sa.PrimaryKeyConstraint('contractid')
    )
    op.create_table('engagement',
    sa.Column('engagementid', sa.Integer(), nullable=False),
    sa.Column('capacity_in_days', sa.Integer(), nullable=False),
    sa.Column('hours_of_work', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('contract_rate', sa.String(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.contractid'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profileid'], ),
    sa.PrimaryKeyConstraint('engagementid')
    )
    op.create_table('messages',
    sa.Column('messageid', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('message_sent', sa.DateTime(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.contractid'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profileid'], ),
    sa.PrimaryKeyConstraint('messageid')
    )
    op.add_column('profiles', sa.Column('contractor', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('employer', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'employer')
    op.drop_column('profiles', 'contractor')
    op.drop_table('messages')
    op.drop_table('engagement')
    op.drop_table('contracts')
    # ### end Alembic commands ###
