name: CI/CD
on:
  push:
    branches: [ feature ]
jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Set Up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Tests
        env:
          FLASK_ENV: testing
          AWS_ACCESS_KEY_ID: 1
          AWS_SECRET_ACCESS_KEY: 1
          AWS_S3_BUCKET: 1
        run: |
          echo DB_URI=sqlite:///:memory: >> .env
          python -m unittest discover src/tests/
#  deployment:
    #    needs: test_suite
    #    runs-on: ubuntu-latest
    #    steps:
    #      - name: Fresh clone & repo install
    #        uses: appleboy/ssh-action@master
    #        with:
    #          host: 34.194.100.219
    #          username: github-actions
    #          key: ${{ secrets.EC2 }}
    #          port: 22
    #          script: |
    #            rm -rf astroapp
    #            git clone https://github.com/Ctrain68/astroapp.git
    #            python3.9 -m venv /home/github-actions/astroapp/venv
    #            source /home/github-actions/astroapp/venv/bin/activate
    #            pip install -r /home/github-actions/astroapp/requirements.txt
